# Generated by Django 5.1.4 on 2025-01-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_user_course_user_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user_make',
            new_name='publisher',
        ),
    ]
