# Generated by Django 5.1.4 on 2025-01-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_video_course_day_video_course_appliedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='State',
            field=models.CharField(choices=[('active', 'active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='State',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
