# Generated by Django 5.1.4 on 2025-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_state_video_state_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='State',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
    ]
